### ISSUE TITLE
Promise support

### ISSUE THREAD

**Issue by Kreozot** [WebReflection/db#6]
Hi!

Do you like an idea to add Promise support? Will you merge a PR which adds it?

And why the lib is abandoned? Is there any better alternative?

**Comment by WebReflection** [comment]
this library was created before [localForage](https://mozilla.github.io/localForage/) but today I'd suggest the latter one instead of this one.

It's been good for the time it's been used, right now I am not planning, neither I have time, to update this library.

I will eventually mark it as deprecated on both README and npm as soon as I remember and have some time.

Best Regards

**Comment by Kreozot** [comment]
Thank you for the quick answer! And thanks for the advice.

It'll be great if you add link to localForage  to the readme.

**Comment by WebReflection** [comment]
there is also another simpler alternative from @jakearchibald called [idb-keyval](https://github.com/jakearchibald/idb-keyval)

I will add these info in the readme
